name: CI/CD Pipeline

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: |
          docker build -t backend:latest backend
          docker build -t frontend:latest frontend
      - uses: aws-actions/amazon-ecr-login@v2
      - run: |
          docker tag backend:latest ${{ secrets.ECR_BACKEND }}
          docker tag frontend:latest ${{ secrets.ECR_FRONTEND }}
          docker push ${{ secrets.ECR_BACKEND }}
          docker push ${{ secrets.ECR_FRONTEND }}
      - uses: eks-actions/kubectl@v2
        with:
          args: apply -f k8s/
